### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by burhanxd**
Remade Readme.md with some small changes ...

### CODE REVIEW

**Review by sparsh-99 — CHANGES_REQUESTED** [review]
Hey @coderburhan, Do add the definition and some graphs of Gaussian Binomial Distribution also in the introduction section

**Comment by burhanxd** [comment]
@sparsh-99 i commited some changes as you asked for graphs and defination.

**Review by sparsh-99 — APPROVED** [review]
By now, it's okay to be merged

**Comment by burhanxd** [comment]
yeah..

**Pull request merged**
